all:
  hosts:
    node1:
      ansible_host: 192.168.106.109
      ansible_user: ubuntu
      ip: 192.168.106.109
      access_ip: 192.168.106.109
    node2:
      ansible_host: 192.168.106.116
      ansible_user: ubuntu
      ip: 192.168.106.116
      access_ip: 192.168.106.116
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
